[package]
name = "token"
edition = "2024"

[dependencies]
base64 = { workspace = true, features = ["std"] }
rand = { workspace = true, features = ["thread_rng"] }
sha2 = { workspace = true }
zeroize = { workspace = true }
