[package]
name = "oblivious"
edition = "2024"

[dependencies]
base64 = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
jose-jwk = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }