[package]
name = "seed"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "any",
    "sqlite",
    "postgres",
    "mysql",
] }
